config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions'}
  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'

  resources :activities, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :inscriptions, only: [:new, :create, :index]
    get 'get_xlsx', to: 'inscriptions#get_xlsx'
    resources :articles, only: [:new, :create]
  end

  resources :grown_activities, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :grown_inscriptions, only: [:new, :create, :index]
    get 'get_xlsx', to: 'inscriptions#get_xlsx'
    resources :grown_activity_articles, only: [:new, :create]
  end

  resources :users, only: [:show, :edit, :update] do
    resources :children, only: [:index, :create]
  end

  resources :children, only: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :inscriptions, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :children, through: :inscriptions

  has_attachment :photo

  validates :title, presence: true
  validates :max_participants, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :activity

  validates :title, presence: true
  validates :content, presence: true
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :user
  has_many :inscriptions, dependent: :destroy
  has_many :activities, through: :inscriptions

  validates :first_name, presence: {:message => "Veuillez remplir le prénom de l'enfant"}
  validates_uniqueness_of :first_name, scope: [:user_id], message: "Vous avez déjà un enfant avec ce prénom"
  validates :last_name, presence: {:message => "Veuillez remplir le nom de l'enfant"}
  validates :sex, presence: {:message => "Veuillez remplir le sexe de l'enfant"}
  validates :sex, inclusion: { in: ["Garçon", "Fille"] }
  validates :birth_date, presence: {:message => "Veuillez remplir la date de naissance"}
  validates :school, presence: {:message => "Veuillez remplir l'école de l'enfant"}
end

app/models/child_activity.rb
class ChildActivity < ApplicationRecord
end

app/models/grown_activity.rb
class GrownActivity < ApplicationRecord
  has_many :grown_inscriptions, dependent: :destroy
  has_many :grown_activity_articles, dependent: :destroy
  has_many :users, through: :grown_inscriptions

  has_attachment :photo

  validates :title, presence: true
  validates :max_participants, presence: true
end

app/models/grown_activity_article.rb
class GrownActivityArticle < ApplicationRecord
  belongs_to :grown_activity
end

app/models/grown_inscription.rb
class GrownInscription < ApplicationRecord
  belongs_to :grown_activity
  belongs_to :user

  validates :grown_activity_id, presence: true
  validates :user_id, presence: true
  validates_uniqueness_of :user_id, scope: [:grown_activity_id], message: "Vous êtes déjà inscrit à cette activitée"
end

app/models/inscription.rb
class Inscription < ApplicationRecord
  acts_as_xlsx
  belongs_to :child
  belongs_to :activity

  validates :activity_id, presence: true
  validates :child_id, presence: {:message => "Veuillez selectionner un enfant"}
  validates_uniqueness_of :child_id, scope: [:activity_id], message: "Cet enfant est déjà inscrit à cette activitée"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :children, dependent: :destroy
  has_many :grown_inscriptions, dependent: :destroy
  has_many :grown_activities, through: :grown_inscriptions

  validates :civility, presence: {:message => "Veuillez remplir ce champ"}
  validates :civility, inclusion: { in: ["M.", "Mme" , "Mlle"] }
  validates :first_name, presence: {:message => "Veuillez remplir ce champ"}
  validates :last_name, presence: {:message => "Veuillez remplir ce champ"}
  validates :address, presence: {:message => "Veuillez remplir ce champ"}
  validates :main_phone, presence: {:message => "Veuillez remplir ce champ"}
  validates :main_phone, format: {:with => /\A(\+\d{2}\s?|0)\d\s?(\d\s?){8}\Z/, :message => "Veuillez renseigner un téléphone français" }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @activity = Activity.find(params[:activity_id])
    @article = Article.new(activity: @activity)
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    authorize @article
    @activity = @article.activity
    if @article.save
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :activity_id)
  end
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController

  before_action :set_user, only: [:new, :edit, :index]
  before_action :set_child, only: [:edit, :update, :destroy]
  after_filter :save_my_previous_url, only: [:new]


  def index
    @children = policy_scope(Child).where(user: @user).order(birth_date: :desc)
  end

  def create
    @child = Child.new(child_params)
    authorize @child
    @user = @child.user
    puts "-----------------------------------------"
    p params
    p @inscription
    p @activity
    if @child.save
      respond_to do |format|
        format.html { redirect_to session[:my_previous_url] || user_path(current_user) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

  def edit
  end

  def update
    @user = @child.user
    if @child.update(child_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @child.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user) }
      format.js
    end
  end

  private

  def save_my_previous_url
    # session[:previous_url] is a Rails built-in variable to save last url.
    session[:my_previous_url] = URI(request.referer || '').path
  end

  def set_child
    @child = Child.find(params[:id])
    authorize @child
  end

  def set_user
    @user = current_user
  end

  def child_params
    params.require(:child).permit(:first_name, :last_name, :sex, :birth_date, :school, :classe, :extra_info, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  protected

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || session.delete(:back_url) || root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  def show
    @child = Child.new
    @children = Child.where(user: @user)
  end

  def edit
  end

  def update
    @children = @user.children
    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to user_path(@user) }
        format.js
      end
    else
      respond_to do |format|
       format.html { render 'users/show' }
       format.js
     end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  def user_params
    params.require(:user).permit(:email, :civility, :first_name, :last_name, :address, :main_phone, :secondary_phone)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/grown_activities_helper.rb
module GrownActivitiesHelper
end

app/helpers/inscriptions_helper.rb
module InscriptionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <h1>Création d'article</h1>

      <%= simple_form_for [@activity, @article] do |f| %>

        <div class="form-inputs">
          <%= f.input :title, label: "Titre de l'article" %>


          <%= f.input :content, as: :text, input_html: {class: "edit-froala"} %>

          <%= f.hidden_field :activity_id, value: @activity.id %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Créer l'article", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_modal_edit.html.erb
<div class="container-fluid">
    <%= simple_form_for(user, remote: true) do |f| %>

      <div class="form-inputs">
        <%= f.input :email, required: true, autofocus: true %>
        <%= f.input :civility, label: "Civilité", :collection => [ "M.", "Mme", "Mlle"]%>
        <%= f.input :first_name, label: "Prénom" %>
        <%= f.input :last_name, label: "Nom" %>
        <%= f.input :address, label: "Adresse" %>
        <%= f.input :main_phone, label: "Téléphone principal", placeholder: "06 00 00 00 00" %>
        <%= f.input :secondary_phone, label: "Téléphone secondaire", placeholder: "06 00 00 00 00" %>
      </div>

      <div class="form-actions">

      </div>

      <div class="modal-footer">
        <%= f.button :submit, "Modifier mes données", class: "button", id: "user-edit-modal-submit" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>

    <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Modification de vos données</h1>

      <%= simple_form_for @user do |f| %>

        <div class="form-inputs">
          <%= f.input :email, required: true, autofocus: true %>
          <%= f.input :civility, label: "Civilité", :collection => [ "M.", "Mme", "Mlle"]%>
          <%= f.input :first_name, label: "Prénom" %>
          <%= f.input :last_name, label: "Nom" %>
          <%= f.input :address, label: "Adresse" %>
          <%= f.input :main_phone, label: "Téléphone principal" %>
          <%= f.input :secondary_phone, label: "Téléphone secondaire" %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Modifier mes données", class: "button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1>Bienvenue <%= @user.first_name + " " + @user.last_name %></h1>
  <hr>

  <div class="row">
    <div class="col-xs-12 col-sm-5">
      <div class="user-col">
        <div class="user-title">

          <div class="title">
            <h3>Vos informations </h3>
          </div>
          <div class="edit-actions">
            <div class="edit-link" data-toggle="tooltip" data-placement="left" title="Modifier mes informations">
              <%= link_to '#user-edit-modal', "data-toggle" => "modal" do %>
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              <% end %>
            </div>
          </div>
        </div>

        <div class="info-content">
          <table class="user-table">
            <tr>
              <th>E-mail</th>
              <td id="email"><%= @user.email %></td>
            </tr>
            <tr>
              <th>Civilité</th>
              <td id="civility"><%= @user.civility %></td>
            </tr>
            <tr>
              <th>Prénom</th>
              <td id="prenom"><%= @user.first_name %></td>
            </tr>
            <tr>
              <th>Nom</th>
              <td id="nom"><%= @user.last_name%></td>
            </tr>
            <tr>
              <th>Adresse</th>
              <td id="adresse"><%= @user.address%></td>
            </tr>
            <tr>
              <th>Téléphone principal</th>
              <td  id="tel-princ"><%= @user.main_phone%></td>
            </tr>
            <% unless @user.secondary_phone.blank?  %>
              <tr>
                <th>Téléphone secondaire</th>
                <td id="tel-sec"><%= @user.secondary_phone%></td>
              </tr>
            <% end %>
          </table>
        </div>

        <div class="div-link">
          <%= link_to "Modifier vos informations", edit_user_path(@user)%>
        </div>

      </div>
    </div>


    <div class="col-xs-12 col-sm-7">
      <div class="user-col">
        <div class="user-title">

          <div class="title">
            <h3>Vos enfants</h3>
          </div>
          <div class="edit-actions">
            <div class="edit-link" data-toggle="tooltip" data-placement="left" title="Ajouter un enfant">
              <%= link_to '#child-form-modal', "data-toggle" => "modal" do %>
                <i class="fa fa-plus" aria-hidden="true"></i>
              <% end %>
            </div>
            <div class="edit-link" data-toggle="tooltip" data-placement="top" title="Voir les actitivités">
              <%= link_to activities_path do %>
                <i class="fa fa-bicycle" aria-hidden="true"></i>
              <% end %>
            </div>
          </div>
        </div>

        <table class="children-table">
          <thead>
            <th>Prénom</th>
            <th>Date de naissance</th>
            <th>Inscrit aux activités</th>
            <th>Actions</th>
          </thead>
          <tbody class="children-tbody">
          <% @children.each do |child| %>
              <tr id="enfant_<%= child.id %>">
                <td id="prenom_enfant_<%= child.id %>"><%= child.first_name %></td>
                <td id="nom_enfant_<%= child.id %>"><%= child.birth_date %></td>
                <td id="activ_enfant_<%= child.id %>"><%= child.activities.map{ |activity| activity.title + ", "}.join.chop.chop %></td>
                <td id="actions_enfant_<%= child.id %>">
                  <%= link_to '#' do %>
                    <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                  <% end %>
                  &nbsp;
                  <%= link_to edit_child_path(child) do %>
                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  <% end %>
                  &nbsp;
                  <%= link_to child_path(child), method: :delete, data: {confirm: "Etes vous sûr de vouloir supprimer " + child.first_name + " " + child.last_name + " ? \n \n Cette action est irréversible."}, remote: true do %>
                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="div-link">
          <%= link_to "Détails sur les enfants", user_children_path(@user) %>
        </div>
      </div>
    </div>
  </div>
</div>



<!-- Modal edit user -->
<div class="modal fade" id="user-edit-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1 class="modal-title" id="myModalLabel">Modifier vos informations</h1>
      </div>
      <div class="edit-modal-body">
        <%= render 'users/modal_edit', user: @user %>
      </div>
    </div>
  </div>
</div>

<!-- Modal add a child -->
<div class="modal fade" id="child-form-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1 class="modal-title" id="myModalLabel">Modifier vos informations</h1>
      </div>
      <div class="child-form-modal-body">
        <%= render 'children/modal_form', user: @user, child: @child%>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  <% end %>
<% end %>

app/views/users/update.js.erb
// app/views/reviews/create.js.erb
// Here you will write *javascript* that would be executed by the browser
<% if @user.errors.any? %>
  // // Render new review form with errors
  // $('#user-edit-modal').modal('show')
  $('.edit-modal-body').html("<%= j render 'users/modal_edit', user: @user %>");

<% else %>

  // fermeture de la modal
   $('#user-edit-modal').modal('hide');


  // mise à jour des données utilisateur
  $("#email").html("<%= @user.email %>").slideDown();
  $("#civility").html("<%= @user.civility %>").slideDown();
  $("#prenom").html("<%= @user.first_name %>").slideDown();
  $("#nom").html("<%= @user.last_name %>").slideDown();
  $("#adresse").html("<%= @user.address %>").slideDown();
  $("#tel-princ").html("<%= @user.main_phone %>").slideDown();
  $("#tel-sec").html("<%= @user.secondary_phone %>").slideDown();

  // refraichit le formulaire avec les nouvelles infos
  $('.edit-modal-body').html("<%= j render 'users/modal_edit', user: @user %>");

<% end %>