config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions'}
  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'

  resources :activities, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :inscriptions, only: [:new, :create, :index]
    get 'get_xlsx', to: 'inscriptions#get_xlsx'
    resources :articles, only: [:new, :create]
  end

  resources :grown_activities, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :grown_inscriptions, only: [:new, :create, :index]
    get 'get_xlsx', to: 'inscriptions#get_xlsx'
    resources :grown_activity_articles, only: [:new, :create]
  end

  resources :users, only: [:show, :edit, :update] do
    resources :children, only: [:index, :create]
  end

  resources :children, only: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :inscriptions, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :children, through: :inscriptions

  has_attachment :photo

  validates :title, presence: true
  validates :max_participants, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :activity

  validates :title, presence: true
  validates :content, presence: true
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :user
  has_many :inscriptions, dependent: :destroy
  has_many :activities, through: :inscriptions

  validates :first_name, presence: {:message => "Veuillez remplir le prénom de l'enfant"}
  validates_uniqueness_of :first_name, scope: [:user_id], message: "Vous avez déjà un enfant avec ce prénom"
  validates :last_name, presence: {:message => "Veuillez remplir le nom de l'enfant"}
  validates :sex, presence: {:message => "Veuillez remplir le sexe de l'enfant"}
  validates :sex, inclusion: { in: ["Garçon", "Fille"] }
  validates :birth_date, presence: {:message => "Veuillez remplir la date de naissance"}
  validates :school, presence: {:message => "Veuillez remplir l'école de l'enfant"}
end

app/models/child_activity.rb
class ChildActivity < ApplicationRecord
end

app/models/grown_activity.rb
class GrownActivity < ApplicationRecord
  has_many :grown_inscriptions, dependent: :destroy
  has_many :grown_activity_articles, dependent: :destroy
  has_many :users, through: :grown_inscriptions

  has_attachment :photo

  validates :title, presence: true
  validates :max_participants, presence: true
end

app/models/grown_activity_article.rb
class GrownActivityArticle < ApplicationRecord
  belongs_to :grown_activity
end

app/models/grown_inscription.rb
class GrownInscription < ApplicationRecord
  belongs_to :grown_activity
  belongs_to :user

  validates :grown_activity_id, presence: true
  validates :user_id, presence: true
  validates_uniqueness_of :user_id, scope: [:grown_activity_id], message: "Vous êtes déjà inscrit à cette activitée"
end

app/models/inscription.rb
class Inscription < ApplicationRecord
  acts_as_xlsx
  belongs_to :child
  belongs_to :activity

  validates :activity_id, presence: true
  validates :child_id, presence: {:message => "Veuillez selectionner un enfant"}
  validates_uniqueness_of :child_id, scope: [:activity_id], message: "Cet enfant est déjà inscrit à cette activitée"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :children, dependent: :destroy
  has_many :grown_inscriptions, dependent: :destroy
  has_many :grown_activities, through: :grown_inscriptions

  validates :civility, presence: {:message => "Veuillez remplir ce champ"}
  validates :civility, inclusion: { in: ["M.", "Mme" , "Mlle"] }
  validates :first_name, presence: {:message => "Veuillez remplir ce champ"}
  validates :last_name, presence: {:message => "Veuillez remplir ce champ"}
  validates :address, presence: {:message => "Veuillez remplir ce champ"}
  validates :main_phone, presence: {:message => "Veuillez remplir ce champ"}
  validates :main_phone, format: {:with => /\A(\+\d{2}\s?|0)\d\s?(\d\s?){8}\Z/, :message => "Veuillez renseigner un téléphone français" }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @activity = Activity.find(params[:activity_id])
    @article = Article.new(activity: @activity)
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    authorize @article
    @activity = @article.activity
    if @article.save
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :activity_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  def show
    @child = Child.new
    @children = Child.where(user: @user)
  end

  def edit
  end

  def update
    @children = @user.children
    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to user_path(@user) }
        format.js
      end
    else
      respond_to do |format|
       format.html { render 'users/show' }
       format.js
     end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  def user_params
    params.require(:user).permit(:email, :civility, :first_name, :last_name, :address, :main_phone, :secondary_phone)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/inscriptions_helper.rb
module InscriptionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cercle culturel et Athlétique de Saint Léon (CASL)</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div id='notice'>
      <%= render 'shared/flashes' %>
    </div>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to "Activités pour les enfants", activities_path %>
<br>
<%= link_to "Activités pour les adultes", grown_activities_path%>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <h1 id="logo-title"><i class="fa fa-home"></i> Jeune de saint leon</h1>
    <!-- ajouter le égal pour faire apparaitre le logo -->
    <% image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

       <!-- Affiche si le user est admin d'une activité -->
        <% unless current_user.activity_admin.blank? %>
          <h3>Vous etes admin de l'activité : <%= current_user.activity_admin %>.&nbsp;&nbsp;&nbsp;&nbsp;</h3>
        <% end %>

        <!-- Affiche si le user est admin -->
        <% if current_user.admin %>
          <h3>Vous etes admin.&nbsp;&nbsp;&nbsp;&nbsp;</h3>
        <% end %>

      <!-- Profile picture and dropdown -->
      <h3>
      <%= link_to user_path(current_user) do %>
        <i class="fa fa-user"></i> <%= current_user.first_name + " " + current_user.last_name %>
      <% end %>
      </h3>

      <div class="navbar-wagon-item">
        <div class="dropdown">

          <h3 class="dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"><i class="fa fa-power-off" aria-hidden="true"></i></h3>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Mon profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Se déconnecter") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->

  <% if user_signed_in? %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to user_path(current_user) do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Mon profil") %>
            <% end %>
          </li>
          <li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Se déconnecter") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to new_user_session_path do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Se connecter") %>
            <% end %>
          </li>
          <li>
        </ul>
      </div>
    </div>
  <% end %>


</div>