config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions'}
  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'

  resources :activities, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :inscriptions, only: [:new, :create, :index]
    get 'get_xlsx', to: 'inscriptions#get_xlsx'
    resources :articles, only: [:new, :create]
  end

  resources :grown_activities, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :grown_inscriptions, only: [:new, :create, :index]
    get 'get_xlsx', to: 'inscriptions#get_xlsx'
    resources :grown_activity_articles, only: [:new, :create]
  end

  resources :users, only: [:show, :edit, :update] do
    resources :children, only: [:index, :create]
  end

  resources :children, only: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/grown_activity.rb
class GrownActivity < ApplicationRecord
  has_many :grown_inscriptions, dependent: :destroy
  has_many :grown_activity_articles, dependent: :destroy
  has_many :users, through: :grown_inscriptions

  has_attachment :photo

  validates :title, presence: true
  validates :max_participants, presence: true
end

app/controllers/grown_activities_controller.rb
class GrownActivitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_grown_activity, only: [:edit, :update, :show, :destroy]

  def index
    # @activities = Activity.all
    @grown_activity = GrownActivity.new
    @grown_activities = policy_scope(GrownActivity)
  end

  def show
    @grown_inscription = GrownInscription.new
    @grown_activity_article = GrownActivityArticle.new(grown_activity: @grown_activity)
  end


  def new
    @grown_activity = GrownActivity.new
    authorize @grown_activity
  end


  def create
    @grown_activity = GrownActivity.new(grown_activity_params)
    # Photo par default si pas de photo choisie
    authorize @grown_activity

    if @grown_activity.save
      url = "http://res.cloudinary.com/dpmc03d5t/image/upload/v1489930552/lp2uzwtcbreav53nzqvc.jpg"
      @grown_activity.photo_url = url if @grown_activity.photo.blank?
      redirect_to grown_activity_path(@grown_activity)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @grown_activity.update(grown_activity_params)
      redirect_to grown_activity_path(@grown_activity)
    else
      render :edit
    end
  end

  def destroy
    @grown_activity.destroy
    redirect_to grown_activities_path
  end

  # private

  def set_grown_activity
    @grown_activity = GrownActivity.find(params[:id])
    authorize @grown_activity
  end

  def grown_activity_params
    params.require(:grown_activity).permit(:title, :subtitle, :max_participants, :photo)
  end
end

app/helpers/grown_activities_helper.rb
module GrownActivitiesHelper
end

app/views/grown_activities/_form.html.erb
<%= simple_form_for @grown_activity do |f| %>

        <div class="form-inputs">
          <%= f.input :title, label: "Titre" %>
          <%= f.input :subtitle, label: "Sous-titre" %>
          <%= f.input :max_participants, label: "Nombre de places" %>
          <%= f.input :photo, as: :attachinary %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Valider", class: "btn btn-primary" %>
        </div>
        <div>
          <%= link_to "Annuler", activities_path %>
        </div>
      <% end %>

app/views/grown_activities/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Modification d'une activité adulte</h1>

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/grown_activities/index.html.erb
<h1>Activités pour les adultes</h1>

<div class="container">
  <div class="row">
    <% if policy(@grown_activity).create? %>
        <p><%= link_to "Ajouter une activité", new_grown_activity_path %></p>
    <% end %>
    <% @grown_activities.each do |grown_activity| %>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="index-card">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path grown_activity.photo.path, height: 300, width: 400, crop: :fill %>');">
            <div class="card-description">
              <h2><%= grown_activity.title %></h2>
              <p><%= grown_activity.subtitle %></p>
            </div>
            <%= link_to grown_activity.title, grown_activity_path(grown_activity), class: "card-link"%>
          </div>
          <% if policy(grown_activity).destroy? %>
            <%= link_to "Supprimer l'activité", grown_activity_path(grown_activity), method: :delete, data: {confirm: "Etes vous sûr de vouloir supprimer cette activité ? \n \n Cette action est iréversible et entraine la supression de la liste des inscrits."} %>
          <% end %>
          <% if policy(grown_activity).update? %>
            <%= link_to "Modifier", edit_grown_activity_path(grown_activity) %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/grown_activities/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Création d'une activitée pour adulte</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/grown_activities/show.html.erb
<div class="container">
  <div class="row">
    <!-- description de l'activité -->
    <div class="col-xs-12 col-sm-9">
      <div class="card-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @grown_activity.photo.path %>');">
          <div class="card-description">
            <h2><%= @grown_activity.title %></h2>
            <p><%= @grown_activity.subtitle %></p>
          </div>
      </div>

      <% @grown_activity.grown_activity_articles.each do |grown_activity_article| %>
        <div class="article">
          <h4><%= grown_activity_article.title%></h4>
          <%= simple_format(grown_activity_article.content)%>
        </div>
        <br>
      <% end %>
    </div>

    <!-- Lien pour inscritption -->
    <div class="col-xs-12 col-sm-3" id="child-inscription">
      <br>
      <% if user_signed_in? %>
        <% if current_user.grown_activities.include?(@grown_activity)%>
          <p id="no-child">Vous êtes déjà inscrit !</p>
        <% else %>
          <p>Vous n'êtes pas encore inscrit à cette activité.</p>
        <% end %>
        <h3> S'inscrire </h3>
        <div id="inscription-form-div">
          <%= render 'grown_inscriptions/form', grown_activity: @grown_activity, grown_inscription: @grown_inscription %>
        </div>
        <br>



      <% else %>
        <h4> Vous souhaitez inscrire votre enfant ?</h4>
        <p>
          <%= link_to "Se connecter", new_user_session_path, class: "btn btn-primary" %>
        </p>
        <p>
          <%= link_to "Créer un compte", new_user_registration_path, class: "btn btn-primary" %>
        </p>
      <% end %>

      <hr>

      <% if policy(@grown_activity).update? %>
        <%= link_to "Modifier l'activité", edit_grown_activity_path(@grown_activity) %>
      <% end %>

      <br>

      <% if policy(@grown_activity_article).create? %>
        <%= link_to "Ajouter un article", new_grown_activity_grown_activity_article_path(@grown_activity) %>
      <% end %>

      <br>

      <% if policy(@grown_activity).index? %>
        <%= link_to "Liste des inscrits", grown_activity_grown_inscriptions_path(@grown_activity) %>
      <% end %>
    </div>
  </div>
</div>