config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions'}
  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'

  resources :activities, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :inscriptions, only: [:new, :create, :index]
    get 'get_xlsx', to: 'inscriptions#get_xlsx'
    resources :articles, only: [:new, :create]
  end

  resources :grown_activities, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :grown_inscriptions, only: [:new, :create, :index]
    get 'get_xlsx', to: 'inscriptions#get_xlsx'
    resources :grown_activity_articles, only: [:new, :create]
  end

  resources :users, only: [:show, :edit, :update] do
    resources :children, only: [:index, :create]
  end

  resources :children, only: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :inscriptions, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :children, through: :inscriptions

  has_attachment :photo

  validates :title, presence: true
  validates :max_participants, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_activity, only: [:edit, :update, :show, :destroy]

  def index
    # @activities = Activity.all
    @activity = Activity.new
    @activities = policy_scope(Activity)
    @grown_activities = policy_scope(GrownActivity)
  end

  def show
    @child = Child.new
    @inscription = Inscription.new
    @article = Article.new(activity: @activity)
  end


  def new
    @activity = Activity.new
    authorize @activity
  end


  def create
    @activity = Activity.new(activity_params)
    # Photo par default si pas de photo choisie
    authorize @activity

    if @activity.save
      url = "http://res.cloudinary.com/dpmc03d5t/image/upload/v1489930552/lp2uzwtcbreav53nzqvc.jpg"
      @activity.photo_url = url if @activity.photo.blank?
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      redirect_to activity_path(@activity)
    else
      render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to activities_path
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
    authorize @activity
  end

  def activity_params
    params.require(:activity).permit(:title, :subtitle, :max_participants, :photo)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= simple_form_for @activity do |f| %>

        <div class="form-inputs">
          <%= f.input :title, label: "Titre" %>
          <%= f.input :subtitle, label: "Sous-titre" %>
          <%= f.input :max_participants, label: "Nombre de places" %>
          <%= f.input :photo, as: :attachinary %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Valider", class: "btn btn-primary" %>
        </div>
        <div>
          <%= link_to "Annuler", activities_path %>
        </div>
      <% end %>

app/views/activities/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Modification d'une activité enfant</h1>

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/activities/index.html.erb
<h1>Activités pour les enfants</h1>

<div class="container">
  <div class="row">
    <% if policy(@activity).create? %>
        <p><%= link_to "Ajouter une activité", new_activity_path %></p>
    <% end %>
    <% @activities.each do |activity| %>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="index-card">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path activity.photo.path, height: 300, width: 400, crop: :fill %>');">
            <div class="card-description">
              <h2><%= activity.title %></h2>
              <p><%= activity.subtitle %></p>
            </div>
            <%= link_to activity.title, activity_path(activity), class: "card-link"%>
          </div>
          <% if policy(activity).destroy? %>
            <%= link_to "Supprimer l'activité", activity_path(activity), method: :delete, data: {confirm: "Etes vous sûr de vouloir supprimer cette activité ? \n \n Cette action est iréversible et entraine la supression de la liste des inscrits."} %>
          <% end %>
          <% if policy(activity).update? %>
            <%= link_to "Modifier", edit_activity_path(activity) %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/activities/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Création d'une activitée</h1>

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/activities/show.html.erb
<div class="container">
  <div class="row">
    <!-- description de l'activité -->
    <div class="col-xs-12 col-sm-9">
      <div class="card-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @activity.photo.path %>');">
          <div class="card-description">
            <h2><%= @activity.title %></h2>
            <p><%= @activity.subtitle %></p>
          </div>
      </div>

      <% @activity.articles.each do |article| %>
        <div class="article">
          <h4><%= article.title%></h4>
          <%= simple_format(article.content)%>
        </div>
        <br>
      <% end %>
    </div>

    <!-- Lien pour inscritption -->
    <div class="col-xs-12 col-sm-3" id="child-inscription">
      <br>
      <% if user_signed_in? %>
        <% if current_user.children.select{ |child| @activity.children.include?(child)}.empty? %>
          <p id="no-child">Vous n'avez aucun enfant inscrit à cette activité pour l'instant.</p>
        <% else %>
          <p>Vos enfants inscrits: </p>
          <ul id="inscrits">
            <% @activity.inscriptions.select{ |inscription| current_user.children.include?(inscription.child)}.each do |inscription|  %>
              <%= render 'inscriptions/show', inscription: inscription %>
            <% end %>
          </ul>
        <% end %>
        <h3> Inscrire mon enfant </h3>
        <div id="inscription-form-div">
          <%= render 'inscriptions/form', activity: @activity, inscription: @inscription %>
        </div>
        <br>
        <br>
        <p>Votre enfant n'apparait pas dans la liste ?</p>
        <%= link_to "Ajouter un enfant",'#child-form-modal', "data-toggle" => "modal" %>


      <% else %>
        <h4> Vous souhaitez inscrire votre enfant ?</h4>
        <p>
          <%= link_to "Se connecter", new_user_session_path, class: "btn btn-primary" %>
        </p>
        <p>
          <%= link_to "Créer un compte", new_user_registration_path, class: "btn btn-primary" %>
        </p>
      <% end %>

      <hr>

      <% if policy(@activity).update? %>
        <%= link_to "Modifier l'activité", edit_activity_path(@activity) %>
      <% end %>

      <br>

      <% if policy(@article).create? %>
        <%= link_to "Ajouter un article", new_activity_article_path(@activity) %>
      <% end %>

      <br>

      <% if policy(@activity).index? %>
        <%= link_to "Liste des inscrits", activity_inscriptions_path(@activity) %>
      <% end %>
    </div>
  </div>
</div>

<% if user_signed_in? %>
<!-- Modal add a child -->
  <div class="modal fade" id="child-form-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h1 class="modal-title" id="myModalLabel">Modifier vos informations</h1>
        </div>
        <div class="child-form-modal-body">
          <%= render 'children/modal_form', user: current_user, child: @child%>
        </div>
      </div>
    </div>
  </div>

<% end %>